Oliver laisikwa CAT 1 Work on Worldometers

Import Libraries and Load Data

In [48]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

Loading  the data from the link

In [9]:
data = "https://www.worldometers.info/population/countries-in-africa-by-population/"
df = pd.read_html(data)[0]
df.head()

,#,Country (or dependency),Population (2024),Yearly Change,Net Change,Density (P/Km²),Land Area (Km²),Migrants (net),Fert. Rate,Med. Age,Urban Pop %,World Share
0,1,Nigeria,232679478,2.10 %,4796533,255,910770,-35202,4.4,18,54 %,2.85 %
1,2,Ethiopia,132059767,2.62 %,3368075,132,1000000,30069,3.9,19,22 %,1.62 %
2,3,Egypt,116538258,1.75 %,2002486,117,995450,123884,2.7,24,41 %,1.43 %
3,4,DR Congo,109276265,3.30 %,3486534,48,2267050,-26968,6.0,16,44 %,1.34 %
4,5,Tanzania,68560157,2.92 %,1942551,77,885800,-29865,4.5,17,39 %,0.84 %

Inspect the data

In [14]:
print(df.head())
print(df.info())

   # Country (or dependency)  Population  (2024) Yearly  Change  Net  Change  \
0  1                 Nigeria           232679478         2.10 %      4796533
1  2                Ethiopia           132059767         2.62 %      3368075
2  3                   Egypt           116538258         1.75 %      2002486
3  4                DR Congo           109276265         3.30 %      3486534
4  5                Tanzania            68560157         2.92 %      1942551

   Density  (P/Km²)  Land Area  (Km²)  Migrants  (net)  Fert.  Rate  \
0               255            910770           -35202          4.4
1               132           1000000            30069          3.9
2               117            995450           123884          2.7
3                48           2267050           -26968          6.0
4                77            885800           -29865          4.5

   Med.  Age Urban  Pop % World  Share
0         18         54 %       2.85 %
1         19         22 %       1.62 %
2         24         41 %       1.43 %
3         16         44 %       1.34 %
4         17         39 %       0.84 %
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   #                        58 non-null     int64
 1   Country (or dependency)  58 non-null     object
 2   Population  (2024)       58 non-null     int64
 3   Yearly  Change           58 non-null     object
 4   Net  Change              58 non-null     int64
 5   Density  (P/Km²)         58 non-null     int64
 6   Land Area  (Km²)         58 non-null     int64
 7   Migrants  (net)          58 non-null     int64
 8   Fert.  Rate              58 non-null     float64
 9   Med.  Age                58 non-null     int64
 10  Urban  Pop %             58 non-null     object
 11  World  Share             58 non-null     object
dtypes: float64(1), int64(7), object(4)
memory usage: 5.6+ KB
None

Clean column names

In [16]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

In [17]:
df.head()

,#,country_(or_dependency),population__(2024),yearly__change,net__change,density__(p/km²),land_area__(km²),migrants__(net),fert.__rate,med.__age,urban__pop_%,world__share
0,1,Nigeria,232679478,2.10 %,4796533,255,910770,-35202,4.4,18,54 %,2.85 %
1,2,Ethiopia,132059767,2.62 %,3368075,132,1000000,30069,3.9,19,22 %,1.62 %
2,3,Egypt,116538258,1.75 %,2002486,117,995450,123884,2.7,24,41 %,1.43 %
3,4,DR Congo,109276265,3.30 %,3486534,48,2267050,-26968,6.0,16,44 %,1.34 %
4,5,Tanzania,68560157,2.92 %,1942551,77,885800,-29865,4.5,17,39 %,0.84 %

Remove unnecessary columns and rows

In [18]:
df = df.drop(columns=['#'])  # Remove the index column
df = df.dropna()  # Drop rows with missing values

In [19]:
df.head()

,country_(or_dependency),population__(2024),yearly__change,net__change,density__(p/km²),land_area__(km²),migrants__(net),fert.__rate,med.__age,urban__pop_%,world__share
0,Nigeria,232679478,2.10 %,4796533,255,910770,-35202,4.4,18,54 %,2.85 %
1,Ethiopia,132059767,2.62 %,3368075,132,1000000,30069,3.9,19,22 %,1.62 %
2,Egypt,116538258,1.75 %,2002486,117,995450,123884,2.7,24,41 %,1.43 %
3,DR Congo,109276265,3.30 %,3486534,48,2267050,-26968,6.0,16,44 %,1.34 %
4,Tanzania,68560157,2.92 %,1942551,77,885800,-29865,4.5,17,39 %,0.84 %

Convert relevant columns to numeric

In [ ]:
data['Population_(2024)'] = pd.to_numeric(data['Population_(2024)'], errors='coerce')
data['Net_Change'] = pd.to_numeric(data['Net_Change'], errors='coerce')
data['Fert._Rate'] = pd.to_numeric(data['Fert._Rate'], errors='coerce')
data['Med._Age'] = pd.to_numeric(data['Med._Age'], errors='coerce')

In [20]:
df.head()

,country_(or_dependency),population__(2024),yearly__change,net__change,density__(p/km²),land_area__(km²),migrants__(net),fert.__rate,med.__age,urban__pop_%,world__share
0,Nigeria,232679478,2.10 %,4796533,255,910770,-35202,4.4,18,54 %,2.85 %
1,Ethiopia,132059767,2.62 %,3368075,132,1000000,30069,3.9,19,22 %,1.62 %
2,Egypt,116538258,1.75 %,2002486,117,995450,123884,2.7,24,41 %,1.43 %
3,DR Congo,109276265,3.30 %,3486534,48,2267050,-26968,6.0,16,44 %,1.34 %
4,Tanzania,68560157,2.92 %,1942551,77,885800,-29865,4.5,17,39 %,0.84 %

Verify cleaned data

In [24]:
print(df.head())
print(df.info())

  country_(or_dependency)  population__(2024) yearly__change  net__change  \
0                 Nigeria           232679478         2.10 %      4796533
1                Ethiopia           132059767         2.62 %      3368075
2                   Egypt           116538258         1.75 %      2002486
3                DR Congo           109276265         3.30 %      3486534
4                Tanzania            68560157         2.92 %      1942551

   density__(p/km²)  land_area__(km²)  migrants__(net)  fert.__rate  \
0               255            910770           -35202          4.4
1               132           1000000            30069          3.9
2               117            995450           123884          2.7
3                48           2267050           -26968          6.0
4                77            885800           -29865          4.5

   med.__age urban__pop_% world__share
0         18         54 %       2.85 %
1         19         22 %       1.62 %
2         24         41 %       1.43 %
3         16         44 %       1.34 %
4         17         39 %       0.84 %
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 58 entries, 0 to 57
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   country_(or_dependency)  58 non-null     object
 1   population__(2024)       58 non-null     int64
 2   yearly__change           58 non-null     object
 3   net__change              58 non-null     int64
 4   density__(p/km²)         58 non-null     int64
 5   land_area__(km²)         58 non-null     int64
 6   migrants__(net)          58 non-null     int64
 7   fert.__rate              58 non-null     float64
 8   med.__age                58 non-null     int64
 9   urban__pop_%             58 non-null     object
 10  world__share             58 non-null     object
dtypes: float64(1), int64(6), object(4)
memory usage: 5.1+ KB
None

Descriptive statistics

In [25]:
print(df.describe())

       population__(2024)   net__change  density__(p/km²)  land_area__(km²)  \
count        5.800000e+01  5.800000e+01         58.000000      5.800000e+01
mean         2.612312e+07  5.925918e+05        131.689655      5.111807e+05
std          3.987530e+07  9.126682e+05        175.534093      5.848486e+05
min          5.237000e+03 -2.419000e+03          2.000000      3.750000e+02
25%          2.525592e+06  4.955050e+04         29.000000      2.868000e+04
50%          1.415218e+07  3.257065e+05         69.500000      2.698000e+05
75%          3.195727e+07  7.406598e+05        131.500000      8.140625e+05
max          2.326795e+08  4.796533e+06        871.000000      2.381740e+06

       migrants__(net)  fert.__rate  med.__age
count        58.000000    58.000000  58.000000
mean     -11108.120690     3.713793  21.413793
std       84518.921666     1.172559   6.808237
min     -544257.000000     1.200000  14.000000
25%      -15323.000000     2.700000  18.000000
50%       -3515.000000     3.800000  19.000000
75%          82.000000     4.300000  22.000000
max      204040.000000     6.000000  51.000000

Get descriptive statistics

In [ ]:
descriptive_stats = data.describe()

In [31]:
df.head()

,country_(or_dependency),population__(2024),yearly__change,net__change,density__(p/km²),land_area__(km²),migrants__(net),fert.__rate,med.__age,urban__pop_%,world__share
0,Nigeria,232679478,2.10 %,4796533,255,910770,-35202,4.4,18,54 %,2.85 %
1,Ethiopia,132059767,2.62 %,3368075,132,1000000,30069,3.9,19,22 %,1.62 %
2,Egypt,116538258,1.75 %,2002486,117,995450,123884,2.7,24,41 %,1.43 %
3,DR Congo,109276265,3.30 %,3486534,48,2267050,-26968,6.0,16,44 %,1.34 %
4,Tanzania,68560157,2.92 %,1942551,77,885800,-29865,4.5,17,39 %,0.84 %

Simple Linear Regression Model

In [4]:
X = data[['Fert._Rate']]
y = data['Population_(2024)']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r_squared = r2_score(y_test, y_pred)
mse = mean_squared_error(y_test, y_pred)

plt.scatter(X_test, y_test, color='blue', label='Actual')
plt.scatter(X_test, y_pred, color='red', label='Predicted')
plt.title('Simple Linear Regression')
plt.xlabel('Fertility Rate')
plt.ylabel('Population (2024)')
plt.legend()
plt.show()

print("R-squared (Simple Regression):", r_squared)
print("Mean Squared Error (Simple Regression):", mse)

NameError: name 'data' is not defined

Multiple Linear Regression

In [5]:
X_multi = data[['Population_(2024)', 'Fert._Rate', 'Med._Age']]
y_multi = data['Net_Change']

X_train_multi, X_test_multi, y_train_multi, y_test_multi = train_test_split(X_multi, y_multi, test_size=0.2, random_state=42)

model_multi = LinearRegression()
model_multi.fit(X_train_multi, y_train_multi)

y_pred_multi = model_multi.predict(X_test_multi)

r_squared_multi = r2_score(y_test_multi, y_pred_multi)
mse_multi = mean_squared_error(y_test_multi, y_pred_multi)

plt.scatter(y_test_multi, y_pred_multi)
plt.title('Multiple Linear Regression')
plt.xlabel('Actual Net Change')
plt.ylabel('Predicted Net Change')
plt.plot([y_test_multi.min(), y_test_multi.max()], [y_test_multi.min(), y_test_multi.max()], 'k--', lw=2)
plt.show()

print("R-squared (Multiple Regression):", r_squared_multi)
print("Mean Squared Error (Multiple Regression):", mse_multi)

NameError: name 'data' is not defined

 Polynomial Regression

In [ ]:
X_poly = data[['Med._Age']]
y_poly = data['Fert._Rate'

Transform the features

In [ ]:
poly = PolynomialFeatures(degree=2)
X_poly_transformed = poly.fit_transform(X_poly)

Split the data

In [ ]:
X_train_poly, X_test_poly, y_train_poly, y_test_poly = train_test_split(X_poly_transformed, y_poly, test_size=0.2, random_state=42)

Create and fit the model

In [ ]:
model_poly = LinearRegression()
model_poly.fit(X_train_poly, y_train_poly)

 Predictions

In [ ]:
y_pred_poly = model_poly.predict(X_test_poly)

Calculate R-squared and Mean Squared Error

In [ ]:
r_squared_poly = r2_score(y_test_poly, y_pred_poly)
mse_poly = mean_squared_error(y_test_poly, y_pred_poly)

Plotting

In [7]:
plt.scatter(y_test_poly, y_pred_poly)
plt.title('Polynomial Regression')
plt.xlabel('Actual Fertility Rate')

NameError: name 'plt' is not defined